### ISSUE TITLE
Relicense to MIT

### ISSUE THREAD

**Issue by furtabs** [NoraTheGamer/Mod-Deobfuscator#2]
I am wanting to relicense this tool under a free license that anyone can use. If you were pinged below please respond with something like  "I permit the license of my contributions to BON2 to be changed to the MIT License" or something like "I do not permit the license of my contributions to BON2 to be changed to the MIT License". Please do not leave us hanging

Permissions Needed:

- [ ] @Choonster - Pending
- [x] @CrankySupertoon - Permission Given
- [ ] @DaemonUmbra - Pending
- [ ] @iLexiconn - Pending
- [ ] @immibis - Pending
- [ ] @LexManos - Pending
- [ ] @Mr-Pyro - Pending
- [ ] @Parker8283 - Pending
- [ ] @tterrag1098 - Pending
- [ ] @VinTarZ - Pending

**Comment by Parker8283** [comment]
Hi Cranky!

Have you attempted to upstream your changes? Lex is obviously pretty active on GH, so if you wanted to PR some of your changes back upstream, I'm sure he would at least take a look at them. As well as tterrag, who appears to still be making incremental updates as needed to it. I could understand this forking/repackaging/relicensing if both versions of it were not being actively maintained, or went a different philosophical direction with development. But as far as I can tell, that hasn't happened here, or perhaps I've missed something.

What do you want to do with your code that LGPL doesn't allow but MIT does? IANAL, but from my understanding, the licenses generally allow you do to the same things, it's just that LGPL comes with some more requirements of having derivative works be open source and changes made when compared to the original work are stated (among other things). And the big one, derivative works must keep the same license, which technically switching to MIT would violate, but you are asking the relicense question, so I believe you would have that covered should you get all the permissions. I'm just confused about why you really want to relicense.

Now, if I were to approve this, it would be kind of a weird position. My code would be allowed to be under a new license of a derivative work, but my work to the upstream projects would still be under a more restrictive license. So for example, if someone made a fork of Lex's project, all contributions at that point are under LGPL, and they would have to abide by those rules. However, if someone forked your project, then they suddenly have less restrictions to abide by. Kind of undercuts the work of the upstream projects in a way, and creates quite the conundrum.

So, at this point currently, I cannot approve of this relicensing. If you have further discussion, I would be happy to talk with you about it.

**Comment by furtabs** [comment]
I can try merging upstream but I doubt Lex will let Yarn mappings get in the software

**Comment by Parker8283** [comment]
Yeah that might be the case, in which case you could also try tterrag's upstream version, I'm not sure how he would feel about it. Barring that, that would be a good reason to fork. However, my other points still stand at that stage.

**Comment by LexManos** [comment]
No you may not relicense my work the current license allows for everything you need, and as for yarn, IDGAF, crowdsourced mappings are crowdsourced and honestly should just be public domain. 

This tool info itself is stupid simple. My changes are essentially a complete rewrite that tterrag can take or not. If you want something for your specific mappings you can either follow the existing license or make your own project. I dont speak for everyone on the upstream project as I am just a fork as well. But typically project dont allow random forks to relicense them for no good reason.

Edit: Actually reviewed your changes. Literally save for about 4 new input validations, ALL you have done is rebranded the project under your own name and take our credits out of it. This is a big hell no from me. Hell you dont ever refer to the original projects by the correct name in the readme. So, sticking with my no. I'd you want to pr yarn mappings in, go for it. If they have a sane system should be like 50 loc. But this is a big yikes.

**Comment by Parker8283** [comment]
To add to Lex's comments, if the upstream maintainers are receptive to upstreaming of work, it would help to prevent some segmentation in the userspace, and create a more cohesive environment for making the best program that can be made. So if you haven't already, I would try to work with the upstream maintainers. It's the beauty of open source! However, if they don't want to accept your changes based on a philosophical difference (ie, Yarn mappings, since both Lex and tterrag work on Forge), then that is an acceptable reason to fork. However, it sounds like Lex is at least willing to review a potential PR, so I would encourage you to at least give that a go.

And Lex mentioning the rebranding, and I would agree with him. Even though I doubt much of my original code still exists in the project, tterrag and Lex have left the package structure and "credits" (in this case I guess the credits would just be the git log, though I guess tterrag has a short sentence on his Jenkins) in tact. It's important to make sure that you keep credit where it's due, especially if you are essentially starting from that base project to make your own thing. While I'm happy that someone else has taken a liking to this project and wants to contribute back in some way, it should be done in such a way that is not destructive to each of the people who have contributed to it.

I would encourage you to make your changes and open a PR to one of the upstream repos that you are based off of. I'm sure there are people who would be happy to have this functionality!

**Comment by LexManos** [comment]
To reiterate on the Yarn issue. I don't know their license, I don't know their structure, I don't know or care much at all about them. And because of that I am not going to put any effort into making my fork use them. However if someone else DOES care they can come along. I'll leave it to someone else/the community to test it and make sure it's done correctly. But if at the end of the day I just have to hit the merge button and it doesn't break anything. I have no issues with it.

People think we have a deep seated hatred of fabric. It's not that, it's that we just don't care. It has nothing to do with us (except for the drama the community likes to drag us into, that's the only part we absolutely hate) 

So again, not opposed, just not going to put much effort into it because I don't care about it.

**Comment by furtabs** [comment]
Fair enough. Let’s give that a shot

**Comment by immibis** [comment]
You may have noticed that my contributions were already MIT to begin with.

**Comment by immibis** [comment]
P.S. Fabric's build system allows you to insert other peoples' mods into the build and it will deobfuscate them as needed. A separate tool is not required.
